/*
gSystem->SetIncludePath("-fopenmp")
gSystem->AddLinkedLibs("-lgomp")
.L openmp.C+O
pi()
*/

/*
Philippe Canal comment to mail Sep 15, 2010
> #pragma omp parallel private(top, bottom)

Humm .. this is going to be a problem :(. The dictionary generated by rootcint (via ACliC) wrap
your code and #defines private to have the value public.

You can try to add before #include <omp.h>

#ifdef private
#undef private
#endif
*/

#ifdef private
#undef private
#endif

#include <omp.h>
#include <time.h>
#include <iostream>

void pi()
{
 const Int_t kN = 100000000;
 long double top = 0.L;
 long double bottom = 0.L;
 long double kStep = 1.L/kN;
 long double sum = 0.L;

#pragma omp parallel private(top, bottom)
 {
#pragma omp for reduction(+:sum)
   for(Int_t i = 0; i < kN; i++) {
     top = 4.L/(1.L + (kStep*i)*(kStep*i));
     bottom = 4.L/(1.L + (kStep*(i+1))*(kStep*(i + 1)));
     sum += (top + bottom)*kStep/2.L;
   } // i
 }
 std::cout.precision(16);
 std::cout << "pi = " << sum << "\n";
}
